/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Hi Spranker
 */
public class profit extends javax.swing.JFrame {

    /**
     * Creates new form profit
     */
    public profit() {
        initComponents();
        outputt.setEditable(false);
        profitfield.setEditable(false);
      lossfield.setEditable(false);
        costfield.setEditable(false);
         pro.setVisible(false);
          loss.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jFrame1 = new javax.swing.JFrame();
        jButton1 = new javax.swing.JButton();
        profitfield = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        costfield = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        outputt = new javax.swing.JTextField();
        lossfield = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        pdfield = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        externalphoto = new javax.swing.JLabel();
        pro = new javax.swing.JLabel();
        loss = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 255, 102));
        jButton1.setText("View Sales Amount");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 280, -1));

        profitfield.setBackground(new java.awt.Color(51, 51, 51));
        profitfield.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        profitfield.setForeground(new java.awt.Color(255, 51, 0));
        profitfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profitfieldActionPerformed(evt);
            }
        });
        getContentPane().add(profitfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, 260, 37));

        jButton2.setBackground(new java.awt.Color(51, 51, 51));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(102, 255, 102));
        jButton2.setText("View Cost Amount");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 290, -1));

        costfield.setBackground(new java.awt.Color(51, 51, 51));
        costfield.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        costfield.setForeground(new java.awt.Color(255, 51, 0));
        costfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                costfieldActionPerformed(evt);
            }
        });
        getContentPane().add(costfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, 260, 40));

        jButton3.setBackground(new java.awt.Color(51, 51, 51));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(102, 255, 102));
        jButton3.setText("VIEW STATUS");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 220, 50));

        outputt.setBackground(new java.awt.Color(51, 51, 51));
        outputt.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        outputt.setForeground(new java.awt.Color(255, 51, 0));
        outputt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outputtActionPerformed(evt);
            }
        });
        getContentPane().add(outputt, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 460, 310, 54));

        lossfield.setBackground(new java.awt.Color(51, 51, 51));
        lossfield.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lossfield.setForeground(new java.awt.Color(255, 51, 0));
        lossfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lossfieldActionPerformed(evt);
            }
        });
        getContentPane().add(lossfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 530, 310, 51));

        jTextField2.setBackground(new java.awt.Color(51, 51, 51));
        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(102, 255, 102));
        jTextField2.setText("Profit Amount");
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 460, 191, 54));

        jTextField3.setBackground(new java.awt.Color(51, 51, 51));
        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(102, 255, 51));
        jTextField3.setText("Loss Amount");
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 530, 191, 51));

        jButton4.setBackground(new java.awt.Color(255, 51, 0));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton4.setText("EXIT");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 255, 102));
        jLabel1.setText("ANALYTICS");
        jLabel1.setFocusTraversalPolicyProvider(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 330, 50));

        jButton5.setBackground(new java.awt.Color(51, 51, 51));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton5.setForeground(new java.awt.Color(102, 255, 102));
        jButton5.setText("Product Damaged Cost");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 310, 40));

        pdfield.setBackground(new java.awt.Color(51, 51, 51));
        pdfield.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        pdfield.setForeground(new java.awt.Color(255, 51, 0));
        getContentPane().add(pdfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 330, 260, 40));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, -1, -1));
        getContentPane().add(externalphoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 140, 90, 60));

        pro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/picture/profit gif.gif"))); // NOI18N
        getContentPane().add(pro, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 20, 540, 360));

        loss.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/picture/loss gif.gif"))); // NOI18N
        getContentPane().add(loss, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 20, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/picture/doit.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
                                
                           
							Class.forName("com.mysql.cj.jdbc.Driver");
							String url = "jdbc:mysql://localhost:3306/inventory";
							String user = "root";
							String pass = "";
							Connection con = DriverManager.getConnection(url, user, pass);
							String sql = "SELECT SUM(totalprice) AS profit FROM salesorder";
                                                        PreparedStatement statement = con.prepareStatement(sql);
                                                        
                                                        
                                                        ResultSet result = statement.executeQuery(sql);
                                                        if(result.next()){
                                                            int price = result.getInt(String.valueOf("profit"));
                                                            profitfield.setText(String.valueOf(price));
                                                        }
                                                        
                                                        
                                                        
                                                        
                          
                       }
                           catch(SQLException f){
                               f.printStackTrace();
                           } catch (ClassNotFoundException ex) {
                               Logger.getLogger(Addproduct.class.getName()).log(Level.SEVERE, null, ex);
                           
                       }
                  
    }//GEN-LAST:event_jButton1ActionPerformed

    private void profitfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profitfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_profitfieldActionPerformed

    private void costfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_costfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_costfieldActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         try {
                                
                           
							Class.forName("com.mysql.cj.jdbc.Driver");
							String url = "jdbc:mysql://localhost:3306/inventory";
							String user = "root";
							String pass = "";
							Connection con = DriverManager.getConnection(url, user, pass);
							String sql = "SELECT SUM(total) AS profit FROM salesorder";
                                                        PreparedStatement statement = con.prepareStatement(sql);
                                                        
                                                        
                                                        ResultSet result = statement.executeQuery(sql);
                                                        if(result.next()){
                                                            int price = result.getInt(String.valueOf("profit"));
                                                            costfield.setText(String.valueOf(price));
                                                        }
                                                        
                                                        
                                                        
                                                        
                          
                       }
                           catch(SQLException f){
                               f.printStackTrace();
                           } catch (ClassNotFoundException ex) {
                               Logger.getLogger(Addproduct.class.getName()).log(Level.SEVERE, null, ex);
                           
                       }
                  
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
       
     
        outputt.setEditable(false);
        lossfield.setEditable(false);
        int num1 = Integer.parseInt(profitfield.getText());
                                int num2 = Integer.parseInt(costfield.getText());
                                int num3 = Integer.parseInt(pdfield.getText());
                                if(num1>num2+num3){
                                    pro.setVisible(true);
                                    int kkk = num2+num3;
                                int pq = num1-kkk;
                               outputt.setText(Integer.toString(pq));
                                
                               lossfield.setText("NO LOSS");
                                }
                                
                                else if(num1<num2+num3){
                                    loss.setVisible(true);
                                    int yyy = num2+num3;
                                    int qq = yyy-num1;
                                    lossfield.setText(Integer.toString(qq));
                                    outputt.setText("NO PROFIT");
                                }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void outputtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outputtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_outputtActionPerformed

    private void lossfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lossfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lossfieldActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
         try {
                                
                           
							Class.forName("com.mysql.cj.jdbc.Driver");
							String url = "jdbc:mysql://localhost:3306/inventory";
							String user = "root";
							String pass = "";
							Connection con = DriverManager.getConnection(url, user, pass);
							String sql = "SELECT SUM(total) AS pd FROM productdamaged";
                                                        PreparedStatement statement = con.prepareStatement(sql);
                                                        
                                                        
                                                        ResultSet result = statement.executeQuery(sql);
                                                        if(result.next()){
                                                            int price = result.getInt(String.valueOf("pd"));
                                                            pdfield.setText(String.valueOf(price));
                                                        }
                                                        
                                                        
                                                        
                                                        
                          
                       }
                           catch(SQLException f){
                               f.printStackTrace();
                           } catch (ClassNotFoundException ex) {
                               Logger.getLogger(Addproduct.class.getName()).log(Level.SEVERE, null, ex);
                           
                       }
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(profit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(profit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(profit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(profit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new profit().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField costfield;
    private javax.swing.JLabel externalphoto;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel loss;
    private javax.swing.JTextField lossfield;
    private javax.swing.JTextField outputt;
    private javax.swing.JTextField pdfield;
    private javax.swing.JLabel pro;
    private javax.swing.JTextField profitfield;
    // End of variables declaration//GEN-END:variables
}
